# ros2_control controller manager + controllers
controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz

    forward_effort_controller:
      type: forward_command_controller/ForwardCommandController
    forward_position_controller:
      type: forward_command_controller/ForwardCommandController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

forward_effort_controller:
  ros__parameters:
    joints:
      - Wheel_rr_joint
      - Wheel_rl_joint
      - Wheel_fr_joint
      - Wheel_fl_joint
    interface_name: effort
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity

forward_position_controller:
  ros__parameters:
    joints:
      - Steering_fr_joint
      - Steering_fl_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity